export const jobIndustryDropdownData = [
  "Tech",
  "Gaming",
  "Saas",
  "something",
  "Blah",
  "Cool",
];

export const jobSeniorityDropdownData = [
  "Seniority",
  "Junior",
  "Intermediate",
  "Senior",
  "Director",
  "VP",
];

export const jobCategoryDropdownData = [
  "Category",
  "Engineering",
  "Marketing",
  "Sales",
  "Operations",
];

export const jobCompanySizeDropdownData = [
  "0-10",
  "10-50",
  "50-100",
  "100-200",
  "200-500",
  "500+",
];

export const stateProvince = [
  "--CANADA--",
  "Alberta",
  "British Columbia",
  "Manitoba",
  "New Brunswick",
  "Newfoundland and Labrador",
  "Northwest Territories",
  "Nova Scotia",
  "Nunavut",
  "Ontario",
  "Prince Edward Island",
  "Quebec",
  "Saskatchewan",
  "Yukon Territory",
  "--USA--",
  "Alaska",
  "Alabama",
  "Arkansas",
  "American Samoa",
  "Arizona",
  "California",
  "Colorado",
  "Connecticut",
  "District of Columbia",
  "Delaware",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Iowa",
  "Idaho",
  "Illinois",
  "Indiana",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Massachusetts",
  "Maryland",
  "Maine",
  "Michigan",
  "Minnesota",
  "Missouri",
  "Mississippi",
  "Montana",
  "North Carolina",
  " North Dakota",
  "Nebraska",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "Nevada",
  "New York",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Virginia",
  "Virgin Islands",
  "Vermont",
  "Washington",
  "Wisconsin",
  "West Virginia",
  "Wyoming",
];
