export const positionCategoryDropdownArray = [
  "Account Mgmt.",
  "Back-End Dev",
  "Customer Success",
  "Data Analysis/Science",
  "Design-UX/UI",
  "Front-End Dev",
  "HR/Recruiting",
  "Marketing",
  "Operations",
  "Product Management",
  "Quality Assurance",
  "Sales/BD",
  "Software Eng",
  "Other Professional",
];

export const YearsOfExperienceDropdownArray = [
  "1-2 Years",
  "2-5 Years",
  "5-8 Years",
  "8-10 Years",
  "10-15 Years",
  "15+ Years",
];

export const InterviewStageDropdownArray = [
  "Technical Interview",
  "Case Study/Code Review",
  "Panel Interview",
  "Final Interview",
];

export const SeniorityDropdownArray = [
  "Junior (1-2 Years)",
  "Intermediate (3-5 Years)",
  "Senior (5-8 Years)",
  "Manager",
  "Director",
  "VP",
  "SVP/Executive",
];

export const BaseSalaryDropdownArray = [
  "<$75k/year",
  "$75k - $90k/year",
  "$90k - $110k/year",
  "$110k - $130k/year",
  "$130k - $150k/year",
  "$150k - $170k/year",
  "$170k - $190k/year",
  "$190k - $210k/year",
  "$210k - $250k/year",
  "$250k+/year",
];

export const RoleSkillDropdownArray = [
  "Industry Expert",
  "International Teams Exp",
  "Strong Technical Chops",
  "Product Vision",
  "Project Management",
  "Versatile Programming Skills",
  "Understands the Customer",
  "Cross-Functional Team Exp",
  "Great Design Eye",
];

export const IntPersonalSkillDropdownArray = [
  "Confident",
  "Effective Communicator",
  "Positive Personality",
  "Team Oriented",
  "Managing/Coaching Exp",
  "Strategic Thinker",
  "Critical Thinker",
  "Strong Business Acumen",
];

export const generalStrengthsDropdownArray = [
  "Experience with international teams ",
  "Clear and effective communicator",
  "Positive energy",
  "Team oriented",
  "Experienced people manager",
  "Strategic thinker",
  "Critical thinker",
  "Strong business acumen",
  "Industry expert",
  "Cross functional team experience",
];

export const InterviewStrengthSkillDropdownArray = [
  "Asked Good Questions",
  "Well Prepared For Interview",
  "Strong Presentation Skills",
  "Polished and Professional",
  "Active Listener",
  "Impressive Technical Assignment",
  "Confident",
];

export const industryArrayList = [
  "Advertising",
  "Hardware",
  "Software",
  "Digital",
  "Media",
  "Finance",
  "Health",
  "Gaming",
  "Education",
  "Ecommerce",
  "Marketing",
  "News and Entertainment",
  "Professional Services",
  "Other-not listed",
];

export const jobCompanySizeDropdownData = [
  "0-10",
  "11-50",
  "51-100",
  "101-250",
  "251-500",
  "500+",
];

export const stateProvinceDropdownArray = [
  "Alberta",
  "British Columbia",
  "Manitoba",
  "New Brunswick",
  "Newfoundland and Labrador",
  "Northwest Territories",
  "Nova Scotia",
  "Nunavut",
  "Ontario",
  "Prince Edward Island",
  "Quebec",
  "Saskatchewan",
  "Yukon Territory",
  "Alaska",
  "Alabama",
  "Arkansas",
  "American Samoa",
  "Arizona",
  "California",
  "Colorado",
  "Connecticut",
  "District of Columbia",
  "Delaware",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Iowa",
  "Idaho",
  "Illinois",
  "Indiana",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Massachusetts",
  "Maryland",
  "Maine",
  "Michigan",
  "Minnesota",
  "Missouri",
  "Mississippi",
  "Montana",
  "North Carolina",
  " North Dakota",
  "Nebraska",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "Nevada",
  "New York",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Virginia",
  "Virgin Islands",
  "Vermont",
  "Washington",
  "Wisconsin",
  "West Virginia",
  "Wyoming",
];
