import "@testing-library/jest-dom/extend-expect";

test("map array and filter for country", async () => {
  // Arrange
  let a = {
    data: {
      hr_voucher_metadata: [
        {
          candidateId: 51,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "VP of Marketing",
          salaryRange: "$210k - $250k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Experienced people manager",
          standOutSkill2: "Confident",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "vivianlee25@gmail.com",
              candidateFirstName: "Vivian",
              candidateLastName: "Lee",
              candidateId: 51,
            },
          ],
          Vouchee: [
            {
              candidateId: 51,
              companyWebsite: "www.arkadium.com",
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              industry: "Education",
              jobCategory: "Data Analysis/Science",
              linkedIn: "linkedin.com/in/vivianlee25",
              locationCity: "New York",
              locationState: "New York",
              positionTitle: "SVP People Innovation",
              seniority: "SVP/Executive",
              created_at: "2022-01-07T23:07:48.170264+00:00",
              companyName: "Arkadium",
            },
          ],
        },
        {
          candidateId: 77,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Experience with international teams ",
          standOutSkill2: "Well Prepared For Interview",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 57,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$75k - $90k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "Well Prepared For Interview",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "mayu852@my.yorku.ca",
              candidateFirstName: "test",
              candidateLastName: "test",
              candidateId: 57,
            },
          ],
          Vouchee: [
            {
              candidateId: 57,
              companyWebsite: "test",
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              industry: "Software",
              jobCategory: "Customer Success",
              linkedIn: "test",
              locationCity: "test",
              locationState: "New Brunswick",
              positionTitle: "test",
              seniority: "Senior (5-8 Years)",
              created_at: "2022-01-19T00:57:57.436223+00:00",
              companyName: "test",
            },
          ],
        },
        {
          candidateId: 58,
          hrId: "IIfStDSBhjZzrdJl3PbsAMWysj22",
          positionTitle: "Senior Product Manager",
          salaryRange: "$130k - $150k/year",
          stageOfInterview: "Technical Interview",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "Well Prepared For Interview",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "IIfStDSBhjZzrdJl3PbsAMWysj22",
              location: "Toronto",
              companyWebsite: "svrobotics.com",
              corporateName: "Mayu Corp",
              rangeOfEmployees: "200-500",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 59,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Positive energy",
          standOutSkill2: "Polished and Professional",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 60,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$110k - $130k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Team oriented",
          standOutSkill2: "Active Listener",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 61,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "HR Director ",
          salaryRange: "$150k - $170k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "Well Prepared For Interview",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 62,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "test ",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Positive energy",
          standOutSkill2: "Strong Presentation Skills",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 63,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "HR director ",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Positive energy",
          standOutSkill2: "Strong Presentation Skills",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 64,
          hrId: "SUGLhXfOthWBX0pNji7nlXcJqtx1",
          positionTitle: "Test",
          salaryRange: "$110k - $130k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Positive energy",
          standOutSkill2: "Polished and Professional",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "SUGLhXfOthWBX0pNji7nlXcJqtx1",
              location: "New York",
              companyWebsite: "vouchrecruit.com",
              corporateName: "Vouch",
              rangeOfEmployees: "0-10",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 65,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "Hello",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Positive energy",
          standOutSkill2: "Strong Presentation Skills",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 66,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "test",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "Well Prepared For Interview",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 10,
          hrId: "505",
          positionTitle: "Director, User Aquisition",
          salaryRange: "190-210",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Understands the Customer",
          standOutSkill2: "Strong Business Acumen",
          standOutSkill3: "Polished and Professional",
          Company_Data: [
            {
              hrId: "505",
              location: "Toronto",
              companyWebsite: "http://insurancehub.com/",
              corporateName: "Insurance Hub",
              rangeOfEmployees: "251-500",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "danielson@gmail.com",
              candidateFirstName: "Daniel",
              candidateLastName: "Son",
              candidateId: 10,
            },
          ],
          Vouchee: [
            {
              candidateId: 10,
              companyWebsite: "http://dave.com/",
              hrId: "505",
              industry: "Fintech",
              jobCategory: "Back-End Dev",
              linkedIn: "http://linkedin.com/in/dson",
              locationCity: "Montreal",
              locationState: "Quebec",
              positionTitle: "Manager, User Acquisition",
              seniority: "Intermediate (3-5 Years)",
              created_at: "2021-11-12T01:37:24.401547+00:00",
              companyName: "Popeyes Chicken",
            },
          ],
        },
        {
          candidateId: 67,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "Test ",
          salaryRange: "$75k - $90k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "Well Prepared For Interview",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 68,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Team oriented",
          standOutSkill2: "Strong Presentation Skills",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 69,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "test ",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "Well Prepared For Interview",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 70,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "tEst",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "Strong Presentation Skills",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 71,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "test",
          salaryRange: "<$75k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "Strong Presentation Skills",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 72,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$110k - $130k/year",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Team oriented",
          standOutSkill2: "Strong Presentation Skills",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 73,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "Test",
          salaryRange: "$75k - $90k/year",
          stageOfInterview: "Final Interview",
          standOutSkill1: "Team oriented",
          standOutSkill2: "Strong Presentation Skills",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 74,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Positive energy",
          standOutSkill2: "Polished and Professional",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 75,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Strategic thinker",
          standOutSkill2: "Well Prepared For Interview",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "test@gmail.com",
              candidateFirstName: "Test",
              candidateLastName: "test",
              candidateId: 75,
            },
          ],
          Vouchee: [
            {
              candidateId: 75,
              companyWebsite: "test",
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              industry: "Hardware",
              jobCategory: "Back-End Dev",
              linkedIn: "test",
              locationCity: "test",
              locationState: "Manitoba",
              positionTitle: "test",
              seniority: "Intermediate (3-5 Years)",
              created_at: "2022-01-22T00:59:35.904832+00:00",
              companyName: "test",
            },
          ],
        },
        {
          candidateId: 76,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "hello",
          salaryRange: "$90k - $110k/year",
          stageOfInterview: "Final Interview",
          standOutSkill1: "Positive energy",
          standOutSkill2: "Strong Presentation Skills",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 78,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$110k - $130k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Positive energy",
          standOutSkill2: "Polished and Professional",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 79,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "test",
          salaryRange: "$75k - $90k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 80,
          hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
          positionTitle: "Test",
          salaryRange: "$110k - $130k/year",
          stageOfInterview: "Case Study/Code Review",
          standOutSkill1: "Team oriented",
          standOutSkill2: "Active Listener",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "e4OBLRsO4WUaal9Nrr5xgdGnDOQ2",
              location: "Markham",
              companyWebsite: "svrobotics.ca",
              corporateName: "SV Robotics",
              rangeOfEmployees: "10-50",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 81,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "CFO",
          salaryRange: "$250k+/year",
          stageOfInterview: "Final Interview",
          standOutSkill1: "Experience with international teams ",
          standOutSkill2: "Asked Good Questions",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 82,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "CFO",
          salaryRange: "$250k+/year",
          stageOfInterview: "Final Interview",
          standOutSkill1: "Cross functional team experience",
          standOutSkill2: "Confident",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "wcheng04@gmail.com",
              candidateFirstName: "Warren",
              candidateLastName: "Cheng",
              candidateId: 82,
            },
          ],
          Vouchee: [
            {
              candidateId: 82,
              companyWebsite: "www.nike.com",
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              industry: "Ecommerce",
              jobCategory: "Operations",
              linkedIn: "linkedin.com/in/warren-cheng-19b967",
              locationCity: "New York",
              locationState: "New York",
              positionTitle: "DIrector of Finance",
              seniority: "Director",
              created_at: "2022-01-22T19:18:42.657767+00:00",
              companyName: "Nike",
            },
          ],
        },
        {
          candidateId: 83,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "Test Test Test ",
          salaryRange: "<$75k/year",
          stageOfInterview: "Technical Interview",
          standOutSkill1: "Experienced people manager",
          standOutSkill2: "Polished and Professional",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [],
          Vouchee: [],
        },
        {
          candidateId: 84,
          hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
          positionTitle: "Director of Finance ",
          salaryRange: "$75k - $90k/year",
          stageOfInterview: "Final Interview",
          standOutSkill1: "Clear and effective communicator",
          standOutSkill2: "Active Listener",
          standOutSkill3: "",
          Company_Data: [
            {
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              location: "NEW YORK CITY",
              companyWebsite: "www.arkadium.com",
              corporateName: "Arkadium",
              rangeOfEmployees: "50-100",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "wcheng04@gmail.com",
              candidateFirstName: "Warren",
              candidateLastName: "Cheng",
              candidateId: 84,
            },
          ],
          Vouchee: [
            {
              candidateId: 84,
              companyWebsite: "www.arkadium.com",
              hrId: "8MPBVn1klDQwmFhHiCcYLHOA7S73",
              industry: "Hardware",
              jobCategory: "Back-End Dev",
              linkedIn: "linkedin.com/in/warren-cheng-19b967",
              locationCity: "New York",
              locationState: "New York",
              positionTitle: "Director",
              seniority: "Intermediate (3-5 Years)",
              created_at: "2022-01-22T19:48:04.480115+00:00",
              companyName: "Arkadium",
            },
          ],
        },
        {
          candidateId: 1,
          hrId: "501",
          positionTitle: "Software Engineer",
          salaryRange: "110-130",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Industry Experience",
          standOutSkill2: "Confident",
          standOutSkill3: "Active Listener",
          Company_Data: [
            {
              hrId: "501",
              location: "New York",
              companyWebsite: "http://momoneymoproblems.com/",
              corporateName: "momoneymoproblems",
              rangeOfEmployees: "0-10",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "johnunderwood@gmail.com",
              candidateFirstName: "John",
              candidateLastName: "Underwood",
              candidateId: 1,
            },
          ],
          Vouchee: [
            {
              candidateId: 1,
              companyWebsite: "http://www.nerdwallet.com/",
              hrId: "501",
              industry: "fintech",
              jobCategory: "Quality Assurance",
              linkedIn: "http://linkedin.com/in/john-underwood",
              locationCity: "Yes",
              locationState: "California",
              positionTitle: "Software Engineer II",
              seniority: "Director",
              created_at: "2021-11-12T01:19:11.13822+00:00",
              companyName: "Gymnasium",
            },
          ],
        },
        {
          candidateId: 3,
          hrId: "502",
          positionTitle: "Engineering Director",
          salaryRange: "190-210",
          stageOfInterview: "Technical Interview",
          standOutSkill1: "International Team Exp",
          standOutSkill2: "PHP",
          standOutSkill3: "Asked Good Questions",
          Company_Data: [
            {
              hrId: "502",
              location: "New York",
              companyWebsite: "http://abacus.com/",
              corporateName: "Abacus",
              rangeOfEmployees: "11-50",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "liorelrom@gmail.com",
              candidateFirstName: "Lior",
              candidateLastName: "Elrom",
              candidateId: 3,
            },
          ],
          Vouchee: [
            {
              candidateId: 3,
              companyWebsite: "http://wework.com/",
              hrId: "502",
              industry: "real estate",
              jobCategory: "Front-End Dev",
              linkedIn: "https://www.linkedin.com/in/liormb",
              locationCity: "Yes",
              locationState: "Ontario",
              positionTitle: "Engineering Manager",
              seniority: "Junior (1-2 Years)",
              created_at: "2021-11-12T01:24:28.893614+00:00",
              companyName: "Google",
            },
          ],
        },
        {
          candidateId: 5,
          hrId: "503",
          positionTitle: "Manager, Analytics",
          salaryRange: "130-150",
          stageOfInterview: "Final Interview",
          standOutSkill1: "Positive Personality",
          standOutSkill2: "Strong Presentation Skill",
          standOutSkill3: "Polished and Professional",
          Company_Data: [
            {
              hrId: "503",
              location: "Toronto",
              companyWebsite: "http://readme.com/",
              corporateName: "Readme",
              rangeOfEmployees: "51-100",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "lucaswinter@gmail.com",
              candidateFirstName: "Lucas",
              candidateLastName: "Winter",
              candidateId: 5,
            },
          ],
          Vouchee: [
            {
              candidateId: 5,
              companyWebsite: "http://compstak.com/",
              hrId: "503",
              industry: "Software",
              jobCategory: "Sales/BD",
              linkedIn: "http://linkedin.com/in/lucas-winter",
              locationCity: "New York",
              locationState: "Quebec",
              positionTitle: "Senior Data Analyst",
              seniority: "SVP/Executive",
              created_at: "2021-11-12T01:28:17.258595+00:00",
              companyName: "Youtube",
            },
          ],
        },
        {
          candidateId: 2,
          hrId: "501",
          positionTitle: "Engineering Director",
          salaryRange: "190-210",
          stageOfInterview: "Final Interview",
          standOutSkill1: "Great Design eye",
          standOutSkill2: "Managing/Coaching Exp",
          standOutSkill3: "Polished and Professional",
          Company_Data: [
            {
              hrId: "501",
              location: "New York",
              companyWebsite: "http://momoneymoproblems.com/",
              corporateName: "momoneymoproblems",
              rangeOfEmployees: "0-10",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "bryanirace@gmail.com",
              candidateFirstName: "Bryan",
              candidateLastName: "Irace",
              candidateId: 2,
            },
          ],
          Vouchee: [
            {
              candidateId: 2,
              companyWebsite: "http://stripe.com/",
              hrId: "501",
              industry: "fintech",
              jobCategory: "Customer Success",
              linkedIn: "http://linkedin.com/in/bryanirace",
              locationCity: "Yes",
              locationState: "Ontario",
              positionTitle: "Engineering Manager",
              seniority: "Director",
              created_at: "2021-11-12T01:20:53.996164+00:00",
              companyName: "Capital Ventures",
            },
          ],
        },
        {
          candidateId: 4,
          hrId: "502",
          positionTitle: "Director, User Experience",
          salaryRange: "130-150",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Project Management",
          standOutSkill2: "Strategic Thinker",
          standOutSkill3: "Did their hmwk (role/org)",
          Company_Data: [
            {
              hrId: "502",
              location: "New York",
              companyWebsite: "http://abacus.com/",
              corporateName: "Abacus",
              rangeOfEmployees: "11-50",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "johnmccartney@gmail.com",
              candidateFirstName: "John ",
              candidateLastName: "McCartney",
              candidateId: 4,
            },
          ],
          Vouchee: [
            {
              candidateId: 4,
              companyWebsite: "http://communitybrands.com/",
              hrId: "502",
              industry: "finance",
              jobCategory: "Customer Success",
              linkedIn: "http://linkedin.com/in/imjohnmccartney",
              locationCity: "Yes",
              locationState: "Alberta",
              positionTitle: "User Experience Manager",
              seniority: "Director",
              created_at: "2021-11-12T01:26:25.53278+00:00",
              companyName: "Facebook",
            },
          ],
        },
        {
          candidateId: 6,
          hrId: "503",
          positionTitle: "Sr Product Owner",
          salaryRange: "110-130",
          stageOfInterview: "Technical Interview",
          standOutSkill1: "Product Vision",
          standOutSkill2: "Critical Thinkier",
          standOutSkill3: "Asked Good Questions",
          Company_Data: [
            {
              hrId: "503",
              location: "Toronto",
              companyWebsite: "http://readme.com/",
              corporateName: "Readme",
              rangeOfEmployees: "51-100",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "katemukmin@gmail.com",
              candidateFirstName: "Kate",
              candidateLastName: "Mukmin",
              candidateId: 6,
            },
          ],
          Vouchee: [
            {
              candidateId: 6,
              companyWebsite: "http://passport.com/",
              hrId: "503",
              industry: "Software",
              jobCategory: "Product Management",
              linkedIn: "http://linkedin.com/in/kate-mukmin",
              locationCity: "New York",
              locationState: "Ontario",
              positionTitle: "Product Owner",
              seniority: "Senior (5-8 Years)",
              created_at: "2021-11-12T01:30:07.740132+00:00",
              companyName: "Hasura",
            },
          ],
        },
        {
          candidateId: 7,
          hrId: "504",
          positionTitle: "VP People",
          salaryRange: "210-250",
          stageOfInterview: "Panel Interview",
          standOutSkill1: "Cross-Functional Team Exp",
          standOutSkill2: "Team Oriented",
          standOutSkill3: "Strong Presentation Skills",
          Company_Data: [
            {
              hrId: "504",
              location: "Toronto",
              companyWebsite: "http://lab.com/",
              corporateName: "Lab",
              rangeOfEmployees: "101-250",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "shusong@gmail.com",
              candidateFirstName: "Shu",
              candidateLastName: "Song",
              candidateId: 7,
            },
          ],
          Vouchee: [
            {
              candidateId: 7,
              companyWebsite: "http://publicgoods.com/",
              hrId: "504",
              industry: "Ecommerce",
              jobCategory: "Data Analysis/Science",
              linkedIn: "http://linkedin.com/in/songshu",
              locationCity: "Toronto",
              locationState: "Ontario",
              positionTitle: "HR Director",
              seniority: "Junior (1-2 Years)",
              created_at: "2021-11-12T01:32:19.67163+00:00",
              companyName: "Dashboard Inc.",
            },
          ],
        },
        {
          candidateId: 8,
          hrId: "504",
          positionTitle: "Manager Talent",
          salaryRange: "130-150",
          stageOfInterview: "Final Interview",
          standOutSkill1: "Industry Expert",
          standOutSkill2: "Positive Personality",
          standOutSkill3: "Strong Presentation Skills",
          Company_Data: [
            {
              hrId: "504",
              location: "Toronto",
              companyWebsite: "http://lab.com/",
              corporateName: "Lab",
              rangeOfEmployees: "101-250",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "harleenmultani@gmail.com",
              candidateFirstName: "Harleen",
              candidateLastName: "Multani",
              candidateId: 8,
            },
          ],
          Vouchee: [
            {
              candidateId: 8,
              companyWebsite: "spotify.com",
              hrId: "504",
              industry: "Digital",
              jobCategory: "Marketing",
              linkedIn: "http://linkedin.com/in/harleen-multani",
              locationCity: "Toronto",
              locationState: "New York",
              positionTitle: "Talent Aquisition Specialist",
              seniority: "Senior (5-8 Years)",
              created_at: "2021-11-12T01:34:08.212138+00:00",
              companyName: "Zerglings Co.",
            },
          ],
        },
        {
          candidateId: 9,
          hrId: "505",
          positionTitle: "VP User Experience",
          salaryRange: "210-250",
          stageOfInterview: "Technical Interview",
          standOutSkill1: "Strong Technical Chops",
          standOutSkill2: "Effective Communicator",
          standOutSkill3: "Active Listener",
          Company_Data: [
            {
              hrId: "505",
              location: "Toronto",
              companyWebsite: "http://insurancehub.com/",
              corporateName: "Insurance Hub",
              rangeOfEmployees: "251-500",
            },
          ],
          Candidate_Contact: [
            {
              candidateEmail: "katybaker@gmail.com",
              candidateFirstName: "Katy",
              candidateLastName: "Baker",
              candidateId: 9,
            },
          ],
          Vouchee: [
            {
              candidateId: 9,
              companyWebsite: "http://americanexpress.com/",
              hrId: "505",
              industry: "Finance",
              jobCategory: "Product Management",
              linkedIn: "https://www.linkedin.com/in/katymueller",
              locationCity: "Chicago",
              locationState: "Ontario",
              positionTitle: "User Experience Director",
              seniority: "Senior (5-8 Years)",
              created_at: "2021-11-12T01:35:47.38848+00:00",
              companyName: "Vouch Inc.",
            },
          ],
        },
      ],
      shortlist: [],
    },
  };

  // Act
  const question = getArrayMultiplicationQuestion(a, b, Skill.MULTIPLICATION_5);

  // Assert

  expect(question.text).toBe("4 x 3 =");
});
